services:
  db:
    image: mysql:8.4.0
    command: --lc-time-names=pt_BR --mysql-native-password=ON
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    init: true
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql

  report:
    build:
      context: ./report
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ}
      - MAVEN_CONFIG=/home/.m2
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${REPORT_EXTERNAL_PORT}/q/health"
        ]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    init: true
    ports:
      - "${REPORT_EXTERNAL_PORT}:4000"
      - "${REPORT_DEBUG_PORT}:5005"
    restart: always
    volumes:
      - ./report:/home/app
      - $HOME/.m2:/home/.m2

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - NODE_ENV=${NODE_ENV}
      - DB_DATABASE=${DB_DATABASE}
      - DATABASE_URL=${DATABASE_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
         ["CMD", "curl", "-f", "http://host.docker.internal:${SERVER_EXTERNAL_PORT}/graphql?query=%7B__typename%7D"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    init: true
    ports:
      - "${SERVER_EXTERNAL_PORT}:3000"
      - "${SERVER_DEBUG_PORT}:9229"
    restart: always
    volumes:
      - ./server:/home/node/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - NODE_ENV=${NODE_ENV}
    init: true
    ports:
      - "${CLIENT_EXTERNAL_PORT}:8080"
    restart: always
    volumes:
      - ./client:/home/node/app

volumes:
  db:
