/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.Client;
import org.example.jooq.tables.FlywaySchemaHistory;
import org.example.jooq.tables.Invoice;
import org.example.jooq.tables.InvoiceItem;
import org.example.jooq.tables.Product;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>client</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>invoice</code>.
     */
    public static final Invoice INVOICE = Invoice.INVOICE;

    /**
     * The table <code>invoice_item</code>.
     */
    public static final InvoiceItem INVOICE_ITEM = InvoiceItem.INVOICE_ITEM;

    /**
     * The table <code>product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;
}
