/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<number, number, number>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface PrismaMigration {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Date | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Date | null;
  started_at: Generated<Date>;
}

export interface Customer {
  document: string;
  id: Generated<number>;
  name: string;
}

export interface Invoice {
  customer_id: number;
  date_time: Date;
  id: Generated<number>;
}

export interface InvoiceItem {
  amount: Decimal;
  id: Generated<number>;
  invoice_id: number;
  product_id: number;
  unit_value: Decimal;
}

export interface Product {
  id: Generated<number>;
  name: string;
}

export interface DB {
  _prisma_migrations: PrismaMigration;
  customer: Customer;
  invoice: Invoice;
  invoice_item: InvoiceItem;
  product: Product;
}
